image: node:latest

stages:
  - install_deps
  - pack_local

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist/

install_deps:
  stage: install_deps
  script:
    - npm install --registry=http://registry.npm.taobao.org
  only:
    - dev
    - master
  tags:
    - node
    - fed

pack_local:
  stage: pack_local
  script:
    - npm run upload local -- --commitid `git rev-parse HEAD` --branch `git name-rev --name-only HEAD`
  only:
    - dev
  tags:
    - node
    - fed
  artifacts:
    paths:
      - dist/test-vuex.zip
